apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/gbenhaim-tenant/python-acs/devfile-sample-python-basic@sha256:88d3aa17cbcc665a55c24f44dfdfcc27ba65bd3e46fbd6f2b8518f3b2906bf36
        name: my-python
        resources: {}
status: {}
